# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_remove_sheet_number_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='number_of_pages',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
